package domain

import "time"

// PersonaStatus describes the lifecycle state of a saved persona.
type PersonaStatus string

const (
	PersonaStatusAvailable PersonaStatus = "available" // ready to use for a new campaign
	PersonaStatusInUse     PersonaStatus = "in_use"    // currently assigned to a running campaign
	PersonaStatusUsed      PersonaStatus = "used"      // successfully used; account created
	PersonaStatusFailed    PersonaStatus = "failed"    // tried, failed; kept for manual review
)

// Persona holds identity data used to create a platform account (Google, Instagram, etc.).
// Personas are either manually entered or auto-generated by the AI tool chain inside a workflow.
type Persona struct {
	ID        string        `json:"id"`
	Kind      string        `json:"kind"`      // "google" | "instagram"
	FirstName string        `json:"firstName"`
	LastName  string        `json:"lastName"`
	Gender    string        `json:"gender,omitempty"`    // "male" | "female"
	BirthDate string        `json:"birthDate,omitempty"` // "YYYY-MM-DD"
	Email     string        `json:"email,omitempty"`
	Username  string        `json:"username,omitempty"`
	Password  string        `json:"password,omitempty"`
	Status    PersonaStatus `json:"status"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

func NewPersonaID() string { return "persona-" + newID() }
